const assert=require('node:assert/strict');
const {MongoMemoryReplSet}=require('mongodb-memory-server');
const mongoose=require('mongoose');
const XLSX=require('xlsx');
const {fields,normalizePhone,validateRow}=require('../services/leadValidation');
const valid=(brand='Alpha',phone='3054447156')=>({brandName:brand,phone,email:'',leadType:'Premium',perDayOrders:'15',extractedFrom:'TikTok',extractedBy:'Manual',followers:'22k',socialActivity:'Active',matureConfidence:'50%',productDetails:'Glass Items',websiteUrl:'',socialLink:'https://example.test/social'});
(async()=>{
 for(const phone of ['03054447156','3054447156','923054447156','+92 305 4447156','00923054447156'])assert.equal(normalizePhone(phone),'+923054447156');
 assert.equal(normalizePhone('123'),null);assert.equal(validateRow(valid()).data.matureConfidence,50);
 assert.equal(validateRow({...valid(),matureConfidence:0}).errors.length,0);
 assert(validateRow({...valid(),socialLink:''}).errors.some(error=>error.includes('Social Link')));
 assert(validateRow({...valid(),matureConfidence:101}).errors.length);
 const repl=await MongoMemoryReplSet.create({binary:{version:'8.2.6',downloadDir:require('path').resolve('.test-mongodb'),...(require('fs').existsSync('.test-mongodb/mongod.exe')?{systemBinary:require('path').resolve('.test-mongodb/mongod.exe')}:{})},replSet:{count:1}});
 process.env.JWT_SECRET='disposable-management-test-only-secret';
 const {app,server,io}=require('../server');
 try{
 await mongoose.connect(repl.getUri());
 const User=require('../models/User'),Lead=require('../models/Lead'),Rejected=require('../models/RejectedLead'),Group=require('../models/LeadGroup'),Activity=require('../models/LeadActivity');
 await Promise.all([User,Lead,Rejected,Group,Activity,require('../models/CallAttempt'),require('../models/LeadImport')].map(model=>model.init()));
 const password=await require('bcryptjs').hash('test-password-123',4);
 const admin=await User.create({name:'Admin',email:'admin@example.test',password,role:'admin'});
 const caller=await User.create({name:'Caller',email:'caller@example.test',password,role:'calling_agent'});
 const second=await User.create({name:'Second',email:'second@example.test',password,role:'calling_agent'});
 const uploader=await User.create({name:'Uploader',email:'uploader@example.test',password,role:'leads_agent'});
 const other=await User.create({name:'Other Uploader',email:'other@example.test',password,role:'leads_agent'});
 const {issueToken}=require('../contollers/auth');
 const tokens=Object.fromEntries([admin,caller,second,uploader,other].map(user=>[user.name,issueToken(user)]));
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}`;
 const api=async(path,actor='Admin',method='GET',body)=>{const response=await fetch(base+path,{method,headers:{...(actor?{Authorization:`Bearer ${tokens[actor]}`}:{ }),...(body&&!(body instanceof FormData)?{'Content-Type':'application/json'}:{})},...(body?{body:body instanceof FormData?body:JSON.stringify(body)}:{})});return {status:response.status,data:response.headers.get('content-type')?.includes('application/json')?await response.json():await response.text()}};
 assert.equal((await api('/api/admin/auth/login',null,'POST',{identity:uploader.email,password:'test-password-123'})).status,200);
 assert.equal((await api('/api/leads/assigned','Uploader')).status,403);
 for (const path of ['stats','imports']) assert.equal((await api('/api/admin/leads/'+path,'Uploader')).status,200);
 assert.equal((await api('/api/admin/users','Uploader')).status,403);
 assert.equal((await api('/api/leads/manual','Caller','POST',{groupName:'Campaign',lead:valid()})).status,403);
 const signup=await api('/api/auth/signup',null,'POST',{name:'New Agent',email:'new@example.test',username:' New.Agent ',password:'test-password-123',role:'leads_agent'});assert.equal(signup.status,201);assert.equal(signup.data.user.accountState,'pending');
 assert.equal(signup.data.user.username,'new.agent');
 assert.equal((await api('/api/auth/signup',null,'POST',{name:'Duplicate',email:'different@example.test',username:'NEW.AGENT',password:'test-password-123',role:'leads_agent'})).status,409);
 assert.equal((await api('/api/auth/signup',null,'POST',{name:'Invalid',email:'invalid@example.test',username:'bad username',password:'test-password-123',role:'leads_agent'})).status,400);
 assert.equal((await api('/api/admin/auth/login',null,'POST',{identity:'new@example.test',password:'test-password-123'})).status,403);
 assert.equal((await api(`/api/admin/users/${signup.data.user.id}`,'Admin','PATCH',{accountState:'active'})).status,200);
 assert.equal((await api('/api/admin/auth/login',null,'POST',{identity:'new.agent',password:'test-password-123'})).status,200);
 const create=await api('/api/leads/manual','Uploader','POST',{groupName:'Campaign',lead:valid()});assert.equal(create.status,201);let lead=create.data.lead;assert.equal(lead.assignedTo,null);assert.equal(lead.phone,'+923054447156');assert.equal(lead.matureConfidence,50);
 const dup=await api('/api/leads/manual','Uploader','POST',{groupName:' campaign ',lead:valid(' alpha ','03051111111')});assert.equal(dup.status,202);assert.equal(dup.data.rejection.reason,'duplicate');assert.deepEqual(dup.data.rejection.errors,['Brand Name already exists']);
 assert.equal((await Group.countDocuments()),1);
 const invalid=await api('/api/leads/manual','Uploader','POST',{groupName:'Campaign',lead:{...valid('Beta','3052222222'),socialLink:''}});assert.equal(invalid.status,202);
 const rejectedId=invalid.data.rejection._id;
 assert.equal((await api(`/api/leads/rejected/${rejectedId}/resubmit`,'Other Uploader','POST',{lead:valid('Beta','3052222222')})).status,404);
 assert.equal((await api(`/api/leads/rejected/${rejectedId}/resubmit`,'Uploader','POST',{lead:valid('Beta','3052222222')})).status,200);
 assert.equal((await api(`/api/leads/rejected/${dup.data.rejection._id}/resubmit`,'Uploader','POST',{lead:valid(),allowDuplicate:true,reviewReason:'Branch'})).status,202);
 assert.equal((await api(`/api/leads/rejected/${dup.data.rejection._id}/resubmit`,'Admin','POST',{lead:valid(),allowDuplicate:true,reviewReason:'Legitimate alternate branch'})).status,200);
 const concurrency=await Promise.all([1,2].map(()=>api('/api/leads/manual','Uploader','POST',{groupName:'Campaign',lead:valid('Concurrent','3053333333')})));assert.deepEqual(concurrency.map(r=>r.status).sort(),[201,202]);
 const book=XLSX.utils.book_new();const headers=fields.map(f=>f[1]);const toRow=row=>fields.map(([name])=>row[name]);XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet([headers,toRow(valid('Excel Good','3055555555')),toRow({...valid('Excel Bad','3056666666'),socialLink:''}),toRow(valid('Alpha','3057777777')),toRow(valid('Excel Good','3055555555'))]),'Leads');
 const form=new FormData();form.append('groupName','Campaign');form.append('file',new Blob([XLSX.write(book,{type:'buffer',bookType:'xlsx'})]),'leads.xlsx');
 const imported=await api('/api/leads/import','Uploader','POST',form);assert.equal(imported.status,201,JSON.stringify(imported.data));assert.deepEqual(imported.data.summary,{totalRows:4,accepted:1,rejected:3,duplicates:2});
 assert.equal(imported.data.rejections.length,3);assert.equal(imported.data.rejections[0].sourceRow,3);assert(imported.data.rejections[0].errors.some(error=>error.includes('Social Link')));
 const batchQueue=await api(`/api/leads/rejected?importBatch=${imported.data.import._id}`,'Uploader');assert.equal(batchQueue.data.pagination.total,3);
 assert.equal((await api(`/api/leads/rejected?importBatch=${imported.data.import._id}`,'Other Uploader')).data.pagination.total,0);
 assert.equal((await api('/api/leads/rejected?importBatch=bad','Uploader')).status,400);
 const fixedExcel=await api(`/api/leads/rejected/${imported.data.rejections[0]._id}/resubmit`,'Uploader','POST',{lead:valid('Excel Bad','3056666666')});assert.equal(fixedExcel.status,200);
 assert.equal((await api(`/api/leads/rejected?importBatch=${imported.data.import._id}`,'Uploader')).data.pagination.total,2);
 const queue=await api('/api/leads/rejected','Uploader');assert(queue.data.rejections.some(row=>row.importBatch===imported.data.import._id));
 const download=await api('/api/leads/rejected/export','Uploader');assert.equal(download.status,200);assert(download.data.includes('Rejection Reasons'));assert(download.data.includes('already exists'));
 assert.equal((await api('/api/leads','Other Uploader')).data.pagination.total,0);
 assert.equal((await api('/api/leads/assign','Uploader','POST',{leadIds:[lead._id],assignedTo:caller._id})).status,403);
 assert.equal((await api('/api/leads/assign','Admin','POST',{leadIds:[lead._id],assignedTo:caller._id})).status,200);
 let assigned=await api('/api/leads/assigned','Caller');assert.equal(assigned.data.leads.length,1);lead=assigned.data.leads[0];assert.equal(lead.assignmentVersion,1);
 const update={operationId:'test-operation-123',version:lead.version,assignmentVersion:lead.assignmentVersion,status:'contacted',remark:'Spoke to owner',followUpAt:new Date(Date.now()-60000).toISOString(),callAttempt:{outcome:'Connected',direction:'OUTGOING',endedAt:new Date().toISOString(),duration:30}};
 assert.equal((await api(`/api/leads/${lead._id}`,'Second','PATCH',update)).status,409);
 assert.equal((await api(`/api/leads/${lead._id}`,'Caller','PATCH',{...update,callAttempt:{outcome:''}})).status,400);
 const saved=await api(`/api/leads/${lead._id}`,'Caller','PATCH',update);assert.equal(saved.status,200,JSON.stringify(saved.data));assert.equal(saved.data.lead.status,'contacted');assert.equal(saved.data.lead.lastCallDirection,'OUTGOING');assert.equal(saved.data.lead.lastCallOutcome,'Connected');
 assert.equal((await api(`/api/leads/${lead._id}`,'Caller','PATCH',update)).status,200);assert.equal(await Activity.countDocuments({operationId:update.operationId}),1);
 assert.equal((await api(`/api/leads/${lead._id}`,'Caller','PATCH',{...update,operationId:'stale-operation-123'})).status,409);
 const load=await api('/api/leads/workload');const counts=load.data.workload.find(user=>user.id===String(caller._id));assert.equal(counts.pending,1);assert.equal(counts.overdue,1);
 const blankRemark=await api(`/api/leads/${lead._id}`,'Caller','PATCH',{operationId:'blank-remark-check-001',version:saved.data.lead.version,assignmentVersion:lead.assignmentVersion,remark:'   '});
 assert.equal(blankRemark.status,200);assert.equal(blankRemark.data.lead.latestRemark,'Spoke to owner');
 const statusCall=await api('/api/leads/call-record','Caller','PATCH',{operationId:'status-call-check-001',phone:'03001112222',version:0,callStatus:'Interested',leadCategory:'Premium',activity:'Meeting',remark:'  Wants a meeting  ',callAttempt:{outcome:'Interested',direction:'OUTGOING',endedAt:new Date().toISOString(),duration:80}});
 assert.equal(statusCall.status,200,JSON.stringify(statusCall.data));assert.equal(statusCall.data.call.remark,'Wants a meeting');assert.equal(statusCall.data.call.callStatus,'Interested');assert.equal(statusCall.data.call.leadCategory,'Premium');
 assert.equal((await api('/api/leads/call-record','Caller','PATCH',{operationId:'long-remark-check-001',phone:'03001112222',version:0,remark:'x'.repeat(2001),callAttempt:{outcome:'Line Busy'}})).status,400);
 assert.equal((await api('/api/leads/assign','Admin','POST',{leadIds:[lead._id],assignedTo:second._id})).status,400);
 assert.equal((await api('/api/leads/assign','Admin','POST',{leadIds:[lead._id],assignedTo:second._id,reason:'Balance workload'})).status,200);
 assert.equal((await api(`/api/leads/${lead._id}`,'Caller','PATCH',{...update,operationId:'after-transfer-123',version:saved.data.lead.version})).status,409);
 const timeline=await api(`/api/leads/${lead._id}/history`);assert.equal(timeline.data.upload.actor.name,'Uploader');assert(timeline.data.events.some(event=>event.type==='reassigned'));assert(timeline.data.events.some(event=>event.type==='call'));
 const bulkBook=XLSX.utils.book_new();XLSX.utils.book_append_sheet(bulkBook,XLSX.utils.aoa_to_sheet([headers,...Array.from({length:1000},(_,i)=>toRow(valid(`Batch ${i}`,String(3060000000+i))))]),'Leads');
 const bulkForm=new FormData();bulkForm.append('groupName','Large Batch');bulkForm.append('file',new Blob([XLSX.write(bulkBook,{type:'buffer',bookType:'xlsx'})]),'batch.xlsx');
 const began=performance.now();const bulk=await api('/api/leads/import','Uploader','POST',bulkForm);assert.equal(bulk.status,201);assert.equal(bulk.data.summary.accepted,1000);console.log(`1000-row local import accepted in ${Math.round(performance.now()-began)}ms.`);
 const matches=await api(`/api/leads/rejected/${dup.data.rejection._id}/matches`);assert.equal(matches.status,200);assert.equal((await api(`/api/leads/rejected/${dup.data.rejection._id}/matches`,'Uploader')).status,403);
 const queueFixture=await Lead.create(['new','new','won','lost'].map((status,i)=>({...validateRow(valid(`QueueFixture ${i}`,String(3070000001+i))).data,status,uploadedBy:other._id,group:lead.group._id||lead.group,assignedTo:i===1?caller._id:null})));
 await Lead.updateOne({_id:queueFixture[0]._id},{$set:{callStatus:'Line Busy',lastCallOutcome:'Busy',lastCallDirection:'OUTGOING',lastCallDuration:75,activity:'Proposal Sent'}});
 await Lead.updateOne({_id:queueFixture[1]._id},{$set:{callStatus:'Interested',leadCategory:'Premium',followUpAt:new Date(Date.now()+15*86400000)}});
 const assignedProgress=await api('/api/leads/assigned','Caller');assert.deepEqual(assignedProgress.data.progressCounts,{pending:0,inProgress:1,closed:0,dead:0});assert.equal(assignedProgress.data.pagination.total,1);
 assert.equal((await api('/api/leads/assigned?progress=inProgress','Caller')).data.leads.length,1);assert.equal((await api('/api/leads/assigned?progress=invalid','Caller')).status,400);
 const queueAll=await api('/api/leads?q=QueueFixture');assert.deepEqual(queueAll.data.queueCounts,{pending:1,inProgress:1,closed:1,dead:1});assert.equal(queueAll.data.pagination.total,4);
 for(const [queue,index] of [['pending',0],['inProgress',1],['closed',2],['dead',3]]){const filtered=await api(`/api/leads?q=QueueFixture&queue=${queue}`);assert.equal(filtered.data.pagination.total,1);assert.equal(filtered.data.leads[0]._id,String(queueFixture[index]._id));assert.deepEqual(filtered.data.queueCounts,queueAll.data.queueCounts);}
 assert.deepEqual((await api('/api/leads?q=QueueFixture','Uploader')).data.queueCounts,{pending:0,inProgress:0,closed:0,dead:0});
 assert.equal((await api('/api/leads?queue=invalid')).status,400);
 const filters=queueAll.data.filterSections.flatMap(section=>section.filters);assert.equal(filters.length,43);assert.equal(new Set(filters.map(filter=>filter.id)).size,43);assert.equal(filters.find(filter=>filter.id==='all').count,4);
 for(const id of ['busy','outbound','active','interested','premium','proposal-sent','registered','dead-lead','future-follow']){assert.equal(filters.find(filter=>filter.id===id).count,1,id);const matches=await api(`/api/leads?q=QueueFixture&leadFilter=${id}`);assert.equal(matches.data.pagination.total,1,id);}
 assert.equal((await api('/api/leads?q=QueueFixture&leadFilter=busy&queue=inProgress')).data.pagination.total,0);
 assert.equal((await api('/api/leads?q=QueueFixture&leadFilter=busy&queue=pending')).data.pagination.total,1);
 assert((await api('/api/leads?q=QueueFixture','Uploader')).data.filterSections.flatMap(section=>section.filters).every(filter=>filter.count===0));
 assert.equal((await api('/api/leads?leadFilter=invalid')).status,400);
 for(const [id,expected] of [['client-assigned',1],['client-dead',1],['client-basic',0],['client-standard',0],['client-premium',4]]){assert.equal(filters.find(filter=>filter.id===id).count,expected,id);assert.equal((await api(`/api/leads?q=QueueFixture&leadFilter=${id}`)).data.pagination.total,expected,id);}
 await Lead.updateOne({_id:queueFixture[0]._id},{$set:{leadCategory:'Basic'}});await Lead.updateOne({_id:queueFixture[2]._id},{$set:{leadCategory:'Standard'}});
 const typedClients=(await api('/api/leads?q=QueueFixture')).data.filterSections.find(section=>section.id==='clients').filters;assert.equal(typedClients.find(filter=>filter.id==='client-basic').count,1);assert.equal(typedClients.find(filter=>filter.id==='client-standard').count,1);assert.equal(typedClients.find(filter=>filter.id==='client-premium').count,2);


 const team=await api('/api/leads/team-performance');assert.equal(team.status,200);assert.equal(team.data.pagination.total,6);
 assert(team.data.users.every(user=>!('password' in user)&&!('token' in user)&&user.createdAt));
 const secondPerformance=team.data.users.find(user=>user.id===String(second._id));assert.equal(secondPerformance.metrics.assigned,1);assert.equal(secondPerformance.metrics.worked,1);assert.equal(secondPerformance.metrics.pending,1);assert.equal(secondPerformance.metrics.overdue,1);assert.equal(secondPerformance.metrics.assignedGroups,1);assert.equal(secondPerformance.metrics.assignedToThem,1);
 const callerPerformance=team.data.users.find(user=>user.id===String(caller._id));assert.equal(callerPerformance.metrics.callAttempts,2);assert.equal(callerPerformance.metrics.assigned,1);assert.equal(callerPerformance.metrics.assignedToThem,1);
 assert.equal(team.data.users.find(user=>user.id===String(admin._id)).metrics.assignedByThem,1);
 assert.equal(team.data.users.find(user=>user.id===String(other._id)).metrics.uploaded,4);
 assert.equal((await api('/api/leads/team-performance','Uploader')).status,403);assert.equal((await api('/api/leads/team-performance','Caller')).status,403);
 const searchedTeam=await api('/api/leads/team-performance?q=new.agent');assert.equal(searchedTeam.data.pagination.total,1);assert.equal(searchedTeam.data.users[0].username,'new.agent');
 assert.equal((await api('/api/leads/team-performance?role=calling_agent')).data.pagination.total,2);
 assert.equal((await api('/api/leads/team-performance?role=invalid')).status,400);
 assert.equal((await api('/api/leads/team-performance?q=nonexistent')).data.pagination.total,0);
 const cards=await api('/api/leads/groups');assert(cards.data.groups.every(group=>group.total===group.assigned+group.remaining));
 assert.equal((await api(`/api/admin/users/${second._id}`,'Admin','PATCH',{accountState:'suspended'})).status,200);
 assert.equal((await api('/api/leads/assigned','Second')).status,401);
 assert.equal((await api('/api/leads/assign','Uploader','POST',{groupIds:[lead.group._id||lead.group],assignedTo:caller._id,mode:'remaining'})).status,403);
 assert.equal((await api('/api/leads/assign','Admin','POST',{groupIds:[lead.group._id||lead.group],assignedTo:caller._id,mode:'reassign'})).status,400);
 const largeGroup=await Group.findOne({name:'Large Batch'});const grouped=await api('/api/leads/assign','Admin','POST',{groupIds:[String(largeGroup._id)],assignedTo:caller._id,mode:'remaining'});assert.equal(grouped.status,200,JSON.stringify(grouped.data));assert.equal(grouped.data.assigned,1000);assert.equal(await Lead.countDocuments({group:largeGroup._id,assignedTo:caller._id}),1000);assert.equal(await Activity.countDocuments({type:'assigned','details.newAgent':String(caller._id)}),1001);
 const beforeGroupMove=await Lead.findOne({group:largeGroup._id}).lean();assert.equal(beforeGroupMove.assignmentVersion,1);
 assert.equal((await api('/api/leads/assign','Admin','POST',{groupIds:[String(largeGroup._id)],assignedTo:caller._id,mode:'remaining'})).status,400);
 await User.updateOne({_id:second._id},{$set:{accountState:'active',isActive:true}});
 const transferredGroup=await api('/api/leads/assign','Admin','POST',{groupIds:[String(largeGroup._id)],assignedTo:second._id,mode:'reassign',reason:'Group handover'});assert.equal(transferredGroup.status,200);assert.equal(transferredGroup.data.assigned,1000);const movedGroupLead=await Lead.findById(beforeGroupMove._id).lean();assert.equal(movedGroupLead.assignmentVersion,2);assert.equal(String(movedGroupLead.assignedTo),String(second._id));assert.equal(await Activity.countDocuments({lead:beforeGroupMove._id,type:'reassigned'}),1);
 assert.equal((await api('/api/leads?q=Second&limit=50')).data.pagination.total,1001);
 const day=new Date(Date.now()+5*3600000).toISOString().slice(0,10),todayStart=new Date(day+'T00:00:00+05:00');await Lead.updateOne({_id:queueFixture[1]._id},{$set:{followUpAt:new Date(todayStart.getTime()+3600000)}});
 const todayList=await api('/api/leads?q=QueueFixture&schedule=today');assert.equal(todayList.status,200);assert.equal(todayList.data.pagination.total,1);assert.equal(todayList.data.todaySchedules,1);assert.equal((await api('/api/leads?q=QueueFixture&schedule=all')).data.pagination.total,1);
 assert.equal((await api('/api/leads?from=2026-02-30')).status,400);assert.equal((await api('/api/leads?from=2026-09-15&to=2026-09-01')).status,400);assert.equal((await api('/api/leads?schedule=wrong')).status,400);
 const dated=await api(`/api/leads?q=QueueFixture&from=${day}&to=${day}`);assert.equal(dated.status,200);assert.equal(dated.data.pagination.total,4);
 assert.equal((await api('/api/leads?q=Batch&limit=100')).data.leads.length,100);
 const fresh=await Lead.findById(lead._id).lean();const edit={operationId:'admin-contact-edit-001',version:fresh.version,assignmentVersion:fresh.assignmentVersion,phone:'03059998888',perDayOrders:'42',remark:'Updated verified contact'};
 assert.equal((await api(`/api/leads/${lead._id}`,'Second','PATCH',edit)).status,403);
 assert.equal((await api(`/api/leads/${lead._id}`,'Admin','PATCH',{...edit,phone:'123'})).status,400);
 assert.equal((await api(`/api/leads/${lead._id}`,'Admin','PATCH',{...edit,phone:'03052222222'})).status,409);
 const edited=await api(`/api/leads/${lead._id}`,'Admin','PATCH',edit);assert.equal(edited.status,200,JSON.stringify(edited.data));assert.equal(edited.data.lead.phone,'+923059998888');assert.equal(edited.data.lead.perDayOrders,'42');assert.equal(edited.data.event.details.changedFields.phone.from,fresh.phone);
 assert.equal((await api(`/api/leads/${lead._id}`,'Admin','PATCH',edit)).status,200);assert.equal(await Activity.countDocuments({operationId:edit.operationId}),1);
 assert.equal((await api(`/api/leads/${lead._id}`,'Admin','PATCH',{...edit,operationId:'admin-contact-stale-001'})).status,409);
 const scheduleEdit={operationId:'admin-schedule-edit-001',version:edited.data.lead.version,assignmentVersion:edited.data.lead.assignmentVersion,followUpAt:new Date(todayStart.getTime()+7200000).toISOString()};
 assert.equal((await api(`/api/leads/${lead._id}`,'Admin','PATCH',scheduleEdit)).status,200);assert.equal((await Lead.findById(lead._id)).followUpAt.toISOString(),scheduleEdit.followUpAt);
 const displayed=await api('/api/leads?q=Alpha');const displayedLead=displayed.data.leads.find(row=>row._id===String(lead._id));assert.equal(displayedLead.latestRemark,'Updated verified contact');assert.equal(displayedLead.lastCallBy.name,'Caller');
 console.log('Management integration checks passed: roles, approval, validation, duplicates, import results, correction, scoped access, assignments, workload, atomic/idempotent updates and history.');
 }finally{await new Promise(resolve=>io.close(resolve));await mongoose.disconnect();await repl.stop();}
})().catch(error=>{console.error(error);process.exitCode=1});
